<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('stock_movements', function (Blueprint $table) {
            // The header of one batch of stock moving: "these parts, these
            // amounts, at this place, paid for by this person, on this date".
            // The lines carry the parts; this row carries the why and the who.
            //
            // The ledger is append-only and is the source of truth for stock:
            //     balance(part, location) = SUM(quantity * direction)
            // over ALL stock_movement_lines, unfiltered. A mistake is corrected
            // by writing an equal-and-opposite `reversal` movement, never by
            // editing or deleting rows. `mistaken` below is an audit flag only
            // and has NO effect on that arithmetic — filtering it out as well
            // as writing a reversal would correct the same error twice.
            $table->id();
            $table->dateTime('moved_at')->index();
            $table->string('type')->index();
            // The default location for this movement's lines; each line still
            // names its own, so a transfer can go from one place to another.
            $table->foreignId('storage_location_id')->nullable()->constrained('storage_locations')->restrictOnDelete();
            $table->string('paid_by')->nullable()->index();
            $table->foreignId('paid_by_technician_id')->nullable()->constrained('technicians')->restrictOnDelete();
            $table->text('body')->nullable();
            // Set when this movement was generated by a part usage drawing from
            // or returning to storage, rather than recorded by hand.
            $table->foreignId('part_usage_id')->nullable()->constrained('part_usages')->nullOnDelete();
            $table->foreignId('reverses_stock_movement_id')->nullable()->constrained('stock_movements')->nullOnDelete();
            $table->boolean('mistaken')->default(false);
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();

            $table->index(['type', 'moved_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('stock_movements');
    }
};
